Tag 1.6.1 - fanart prioritization option
xbmc/metadata.themoviedb.org.python pull request #126
Opened 2022-01-09 11:15 UTC by mkaflowski

Tag 1.6.1 - fanart prioritization option

v1.6.1 (2022-01-09)

Feature: fanart prioritization option
Addressing the problem from: #123

2022-01-09 18:25 UTC, rmrector requested changes

2022-01-09 18:25 UTC, rmrector commented on addon.xml
> +       version="1.6.1+matrix.1"
Do not include the matrix.1 version tag nor change the xbmc.python version. These are both handled by the add-on submission process.

2022-01-09 18:25 UTC, rmrector commented on resources/language/resource.language.en_gb/strings.po
> +msgid "Prioritize fanart artworks over preferred language"
Change to "Prioritize Fanart.TV artworks over preferred language"

2022-01-11 23:12 UTC, rmrector approved these changes

2022-01-13 04:52 UTC, merged

2022-01-14 00:50 UTC, taxigps commented on python/scraper.py
> +            settings)
it's strange to transfer parament settings and settings.getSettingString('language'), may just one parament settings, or two parament settings.getSettingString('language') and settings.getSettingBool('prioritize_fanarttv_artwork')